---
name: junit-tui
version: 0.1.0.0
github: "mfussenegger/junit-tui"
license: GPL-2
author: "Mathias Fußenegger"
maintainer: "github@zignar.net"
copyright: "2020 Mathias Fußenegger"

extra-source-files:
  - README.md
  - ChangeLog.md

description: Please see the README on GitHub at <https://github.com/mfussenegger/junit-tui#readme>

dependencies:
  - base >= 4.7 && < 5
  - text
  - containers
  - xml-conduit
  - brick

library:
  source-dirs: src

executables:
  junit-tui:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - junit-tui

tests:
  junit-tui-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - junit-tui
